[package]
name = "zookeeper-benchmark"
version = "0.1.0"
edition = "2021"
author = ["yangsen.zk@qq.com"]

[dependencies]
clap = { version = "4.1.9", features = ["derive"] }
zookeeper-zk = "0.7"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"